export const REQUEST_ITEMS = 'POST/REQUEST_ITEMS'
export const REQUEST_IN_PROCESS = 'POST/REQUEST_IN_PROCESS'
export const REQUEST_DONE = 'POST/REQUEST_DONE'

export const LOAD_ITEMS = 'POST/LOAD_ITEMS'

export const ADD_ITEM_TO_BASKET = 'BASKET/ADD_ITEM_TO_BASKET'
export const REMOVE_ITEM_TO_BASKET = 'BASKET/REMOVE_ITEM_TO_BASKET'
export const DELETE_ITEM_TO_BASKET = 'BASKET/DELETE_ITEM_TO_BASKET'
export const DELETE_ALL_ITEM_TO_BASKET = 'BASKET/DELETE_ALL_ITEM_TO_BASKET'